"""Runnable example implementation for the XSkill algorithm-kernel API.

Copy this directory to ``~/.xskill/kernels/your-demo-algo-kernel``. The implementation is
deliberately deterministic: it only processes trajectories whose metadata has
``kernel_demo: true``. Replace ``_build_skill_md`` with your own SDK call.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import yaml

from xskill.kernels import (
    BaseKernel,
    KernelContext,
    KernelMetadata,
    KernelRunResult,
    SkillSubmission,
    TrajectoryResource,
)


class YourDemoAlgoKernel(BaseKernel):
    metadata = KernelMetadata(
        id="your-demo-algo-kernel",
        name="Your Demo Algorithm Kernel",
        version="0.1.0",
        description="Runnable template for your own XSkill algorithm kernel.",
        triggers=("scheduled", "manual", "evaluation"),
        api_version=2,
    )

    _DEFAULT_CONFIG = {
        "required_meta_flag": "kernel_demo",
        "max_per_run": 1,
    }

    def run(
        self,
        context: KernelContext,
    ) -> KernelRunResult:
        config = self._load_config(context.config_path)
        cursor_path = context.workspace / "processed.json"
        processed = self._load_processed(cursor_path)
        flag = str(config.get("required_meta_flag") or "kernel_demo")
        max_per_run = int(config.get("max_per_run", 1))
        if max_per_run < 1:
            raise ValueError("max_per_run must be >= 1")

        selected = [
            trajectory
            for trajectory in context.trajectories.list()
            if trajectory.id not in processed
            and bool(trajectory.metadata.get(flag))
        ][:max_per_run]

        submitted: list[str] = []
        for trajectory in selected:
            name = "demo-kernel-" + hashlib.sha256(
                trajectory.id.encode("utf-8")
            ).hexdigest()[:10]
            context.publisher.submit(SkillSubmission(
                name=name,
                skill_md=self._build_skill_md(name, trajectory),
                source_trajectory_ids=(trajectory.id,),
                message=f"demo distillation from {trajectory.id}",
            ))
            submitted.append(name)
            processed.add(trajectory.id)
            # Persist after each successful publication. If a later draft in
            # the same run fails, already-published inputs remain idempotent.
            self._save_processed(cursor_path, processed)

        return KernelRunResult(
            processed_trajectory_ids=tuple(item.id for item in selected),
            submitted_skills=tuple(submitted),
            metrics={
                "selected": len(selected),
                "published": len(submitted),
                "dataset_id": context.invocation.dataset_id,
            },
            notes="Demo kernel only reads metadata.kernel_demo=true inputs.",
        )

    @staticmethod
    def _build_skill_md(name: str, trajectory: TrajectoryResource) -> str:
        """Replace this method with a call to your own algorithm package."""
        excerpt = trajectory.read_text().strip()[:1200]
        quoted_excerpt = "\n".join(
            f"> {line}" if line else ">" for line in excerpt.splitlines()
        )
        return (
            "---\n"
            f"name: {name}\n"
                "description: Skill generated by the demo algorithm kernel.\n"
            "metadata: {}\n"
            "---\n\n"
            f"# {name}\n\n"
            "Replace this deterministic generator with your algorithm SDK.\n\n"
            "## Source excerpt\n\n"
            f"{quoted_excerpt}\n"
        )

    @classmethod
    def _load_config(cls, path: Path) -> dict:
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(
                yaml.safe_dump(cls._DEFAULT_CONFIG, sort_keys=False),
                encoding="utf-8",
            )
        loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(loaded, dict):
            raise ValueError("demo kernel config.yaml must be a mapping")
        return loaded

    @staticmethod
    def _load_processed(path: Path) -> set[str]:
        if not path.exists():
            return set()
        loaded = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(loaded, list):
            raise ValueError("processed.json must contain a JSON list")
        return {str(item) for item in loaded}

    @staticmethod
    def _save_processed(path: Path, processed: set[str]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(".json.tmp")
        temporary.write_text(
            json.dumps(sorted(processed), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        temporary.replace(path)


KERNEL_CLASS = YourDemoAlgoKernel
