"""Bundled kernels: the production native adapter and an opt-in demo."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import yaml

from xskill.kernels.base import (
    BaseKernel,
    KernelManifest,
    KernelRunResult,
    SkillSubmission,
)


class NativeKernel(BaseKernel):
    """Descriptor for the existing TaskAgent -> Cluster -> SkillEdit pipeline."""

    manifest = KernelManifest(
        id="native",
        name="XSkill Native",
        version="1",
        description=(
            "Built-in AtomTask, clustering, SkillEdit and Canary pipeline."
        ),
        triggers=("scheduled", "trajectory_changed", "manual"),
    )

    def run(self, context) -> KernelRunResult:
        del context
        raise RuntimeError("native kernel is executed by the XSkill worker adapter")


class RuleBasedDemoKernel(BaseKernel):
    """Small deterministic kernel used to exercise the public contract.

    It only consumes trajectories whose sidecar metadata contains
    ``kernel_demo: true``.  This guard prevents selecting the demo from turning
    an ordinary production trajectory into a low-quality example skill.
    """

    manifest = KernelManifest(
        id="rule-based-demo",
        name="Rule-based Demo",
        version="1.0",
        description=(
            "Opt-in deterministic example; processes metadata.kernel_demo=true "
            "trajectories without an LLM."
        ),
        triggers=("scheduled", "manual", "evaluation"),
    )

    _DEFAULT_CONFIG = {
        "max_per_run": 1,
        "required_meta_flag": "kernel_demo",
    }

    def run(
        self,
        context,
    ) -> KernelRunResult:
        config = self._load_or_create_config(context.config_path)
        state_path = context.workspace / "processed.json"
        processed = self._load_processed(state_path)
        flag = str(config.get("required_meta_flag") or "kernel_demo")
        max_per_run = int(config.get("max_per_run", 1))
        if max_per_run < 1:
            raise ValueError("rule-based-demo max_per_run must be >= 1")

        eligible = [
            trajectory
            for trajectory in context.trajectories.list()
            if bool(trajectory.metadata.get(flag))
            and trajectory.id not in processed
        ]
        submitted: list[str] = []
        consumed: list[str] = []
        for trajectory in eligible[:max_per_run]:
            digest = hashlib.sha256(trajectory.id.encode("utf-8")).hexdigest()[:10]
            name = f"demo-{digest}"
            body_excerpt = trajectory.read_text().strip()[:1200]
            skill_md = (
                "---\n"
                f"name: {name}\n"
                "description: Demonstration skill generated by the rule-based "
                "kernel contract.\n"
                "metadata:\n"
                "  state: main\n"
                "---\n\n"
                f"# {name}\n\n"
                "This opt-in demo proves that an external algorithm can read a "
                "standard trajectory and publish through XSkill.\n\n"
                "## Source excerpt\n\n"
                f"```text\n{body_excerpt}\n```\n"
            )
            context.publisher.submit(SkillSubmission(
                name=name,
                skill_md=skill_md,
                source_trajectory_ids=(trajectory.id,),
                message=f"distill {trajectory.id}",
            ))
            submitted.append(name)
            consumed.append(trajectory.id)
            processed.add(trajectory.id)

        self._write_processed(state_path, processed)
        return KernelRunResult(
            processed_trajectory_ids=tuple(consumed),
            submitted_skills=tuple(submitted),
            metrics={
                "eligible": len(eligible),
                "published": len(submitted),
                "dataset_id": context.invocation.dataset_id,
            },
            notes="Only metadata-flagged demo trajectories are eligible.",
        )

    @classmethod
    def _load_or_create_config(cls, path: Path) -> dict:
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(
                yaml.safe_dump(cls._DEFAULT_CONFIG, sort_keys=False),
                encoding="utf-8",
            )
        loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if not isinstance(loaded, dict):
            raise ValueError("rule-based-demo config.yaml must be a mapping")
        return loaded

    @staticmethod
    def _load_processed(path: Path) -> set[str]:
        if not path.exists():
            return set()
        loaded = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(loaded, list):
            raise ValueError("rule-based-demo processed.json must be a list")
        return {str(item) for item in loaded}

    @staticmethod
    def _write_processed(path: Path, processed: set[str]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(".json.tmp")
        temporary.write_text(
            json.dumps(sorted(processed), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        temporary.replace(path)


BUILTIN_KERNELS = {
    NativeKernel.manifest.id: NativeKernel,
    RuleBasedDemoKernel.manifest.id: RuleBasedDemoKernel,
}
